// frontend/app/list-builder/page.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  ShoppingCart,
  Plus,
  Wand2,
  Upload,
  Camera,
  FileText,
  Sparkles,
  CheckCircle,
  Clock,
  ArrowRight,
} from "lucide-react"
import Link from "next/link"
import Image from "next/image"

interface GeneratedItem {
  id: string
  name: string
  category: string
  confidence: number
  alternatives: string[]
}

export default function ListBuilderPage() {
  const [inputMethod, setInputMethod] = useState<"manual" | "ai" | "recipe" | "photo">("manual")
  const [manualItem, setManualItem] = useState("")
  const [aiPrompt, setAiPrompt] = useState("")
  const [recipe, setRecipe] = useState("")
  const [generatedItems, setGeneratedItems] = useState<GeneratedItem[]>([])
  const [isGenerating, setIsGenerating] = useState(false)

  const handleManualAdd = () => {
    if (manualItem.trim()) {
      const newItem: GeneratedItem = {
        id: Date.now().toString(),
        name: manualItem,
        category: "Manual",
        confidence: 100,
        alternatives: [],
      }
      setGeneratedItems([...generatedItems, newItem])
      setManualItem("")
    }
  }

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) return

    setIsGenerating(true)

    // Simulate AI processing
    setTimeout(() => {
      const mockItems: GeneratedItem[] = [
        {
          id: "1",
          name: "Organic Chicken Breast (2 lbs)",
          category: "Meat",
          confidence: 95,
          alternatives: ["Free-range Chicken", "Chicken Thighs", "Turkey Breast"],
        },
        {
          id: "2",
          name: "Brown Rice (2 lbs)",
          category: "Grains",
          confidence: 90,
          alternatives: ["Quinoa", "Wild Rice", "Cauliflower Rice"],
        },
        {
          id: "3",
          name: "Mixed Vegetables (Frozen)",
          category: "Produce",
          confidence: 88,
          alternatives: ["Fresh Broccoli", "Stir-fry Mix", "Steam-in-bag Vegetables"],
        },
        {
          id: "4",
          name: "Olive Oil (Extra Virgin)",
          category: "Pantry",
          confidence: 92,
          alternatives: ["Avocado Oil", "Coconut Oil", "Vegetable Oil"],
        },
      ]

      setGeneratedItems([...generatedItems, ...mockItems])
      setIsGenerating(false)
      setAiPrompt("")
    }, 2000)
  }

  const handleRecipeAnalysis = async () => {
    if (!recipe.trim()) return

    setIsGenerating(true)

    // Simulate recipe analysis
    setTimeout(() => {
      const mockRecipeItems: GeneratedItem[] = [
        {
          id: "r1",
          name: "Ground Beef (1 lb)",
          category: "Meat",
          confidence: 98,
          alternatives: ["Ground Turkey", "Plant-based Ground", "Ground Chicken"],
        },
        {
          id: "r2",
          name: "Onion (Large)",
          category: "Produce",
          confidence: 95,
          alternatives: ["Yellow Onion", "Sweet Onion", "Red Onion"],
        },
        {
          id: "r3",
          name: "Canned Tomatoes (14 oz)",
          category: "Pantry",
          confidence: 90,
          alternatives: ["Fresh Tomatoes", "Tomato Sauce", "Crushed Tomatoes"],
        },
        {
          id: "r4",
          name: "Pasta (1 lb)",
          category: "Pantry",
          confidence: 85,
          alternatives: ["Whole Wheat Pasta", "Gluten-free Pasta", "Zucchini Noodles"],
        },
      ]

      setGeneratedItems([...generatedItems, ...mockRecipeItems])
      setIsGenerating(false)
      setRecipe("")
    }, 2500)
  }

  const removeItem = (id: string) => {
    setGeneratedItems(generatedItems.filter((item) => item.id !== id))
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50 h-20">
        <div className="container mx-auto px-4 h-full flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center space-x-3">
            <Image
              src="/images/tangerine-logo.png"
              alt="Tangerine Logo"
              width={60}
              height={60}
              className="rounded-full"
            />
            <h1 className="text-2xl font-bold text-stone-800">tangerine ai list builder</h1>
          </Link>
          <div className="flex items-center space-x-4">
            <Button
              variant="outline"
              asChild
              className="border-stone-300 text-stone-700 hover:bg-stone-50 bg-transparent"
            >
              <Link href="/dashboard">Back to Dashboard</Link>
            </Button>
            {generatedItems.length > 0 && (
              <Button asChild className="bg-orange-500 hover:bg-orange-600 text-white">
                <Link href="/dashboard">
                  Add {generatedItems.length} Items
                  <ArrowRight className="h-4 w-4 ml-2" />
                </Link>
              </Button>
            )}
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-stone-800 mb-4">Build Your Grocery List</h2>
            <p className="text-lg text-stone-600">
              Use AI to generate optimized grocery lists from recipes, meal plans, or natural language
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Input Methods */}
            <div className="space-y-6">
              <Card className="border border-stone-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="text-stone-800">Choose Your Input Method</CardTitle>
                  <CardDescription className="text-stone-600">
                    Select how you'd like to build your grocery list
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Tabs value={inputMethod} onValueChange={(value) => setInputMethod(value as any)}>
                    <TabsList className="grid w-full grid-cols-4 bg-stone-100">
                      <TabsTrigger
                        value="manual"
                        className="text-stone-600 data-[state=active]:bg-white data-[state=active]:text-stone-800"
                      >
                        Manual
                      </TabsTrigger>
                      <TabsTrigger
                        value="ai"
                        className="text-stone-600 data-[state=active]:bg-white data-[state=active]:text-stone-800"
                      >
                        AI Prompt
                      </TabsTrigger>
                      <TabsTrigger
                        value="recipe"
                        className="text-stone-600 data-[state=active]:bg-white data-[state=active]:text-stone-800"
                      >
                        Recipe
                      </TabsTrigger>
                      <TabsTrigger
                        value="photo"
                        className="text-stone-600 data-[state=active]:bg-white data-[state=active]:text-stone-800"
                      >
                        Photo
                      </TabsTrigger>
                    </TabsList>

                    <TabsContent value="manual" className="space-y-4">
                      <div>
                        <h3 className="font-medium mb-2 text-stone-800">Add Items Manually</h3>
                        <p className="text-sm text-stone-600 mb-4">Type grocery items one by one</p>
                        <div className="flex gap-2">
                          <Input
                            placeholder="Enter grocery item (e.g., 'milk', 'bananas', 'chicken')"
                            value={manualItem}
                            onChange={(e) => setManualItem(e.target.value)}
                            onKeyPress={(e) => e.key === "Enter" && handleManualAdd()}
                            className="border-stone-300"
                          />
                          <Button onClick={handleManualAdd} className="bg-orange-500 hover:bg-orange-600">
                            <Plus className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </TabsContent>

                    <TabsContent value="ai" className="space-y-4">
                      <div>
                        <h3 className="font-medium mb-2 text-stone-800">AI-Powered Generation</h3>
                        <p className="text-sm text-stone-600 mb-4">
                          Describe what you want to cook or eat, and AI will generate a grocery list
                        </p>
                        <Textarea
                          placeholder="e.g., 'I want to make healthy meals for a family of 4 this week, including chicken dinners and vegetarian lunches'"
                          value={aiPrompt}
                          onChange={(e) => setAiPrompt(e.target.value)}
                          className="min-h-[100px] border-stone-300"
                        />
                        <Button
                          onClick={handleAIGenerate}
                          disabled={isGenerating || !aiPrompt.trim()}
                          className="w-full mt-2 bg-orange-500 hover:bg-orange-600"
                        >
                          {isGenerating ? (
                            <>
                              <Clock className="h-4 w-4 mr-2 animate-spin" />
                              Generating List...
                            </>
                          ) : (
                            <>
                              <Sparkles className="h-4 w-4 mr-2" />
                              Generate Grocery List
                            </>
                          )}
                        </Button>
                      </div>
                    </TabsContent>

                    <TabsContent value="recipe" className="space-y-4">
                      <div>
                        <h3 className="font-medium mb-2 text-stone-800">Recipe Analysis</h3>
                        <p className="text-sm text-stone-600 mb-4">Paste a recipe and we'll extract the ingredients</p>
                        <Textarea
                          placeholder="Paste your recipe here..."
                          value={recipe}
                          onChange={(e) => setRecipe(e.target.value)}
                          className="min-h-[120px] border-stone-300"
                        />
                        <Button
                          onClick={handleRecipeAnalysis}
                          disabled={isGenerating || !recipe.trim()}
                          className="w-full mt-2 bg-orange-500 hover:bg-orange-600"
                        >
                          {isGenerating ? (
                            <>
                              <Clock className="h-4 w-4 mr-2 animate-spin" />
                              Analyzing Recipe...
                            </>
                          ) : (
                            <>
                              <FileText className="h-4 w-4 mr-2" />
                              Extract Ingredients
                            </>
                          )}
                        </Button>
                      </div>
                    </TabsContent>

                    <TabsContent value="photo" className="space-y-4">
                      <div>
                        <h3 className="font-medium mb-2 text-stone-800">Photo Recognition</h3>
                        <p className="text-sm text-stone-600 mb-4">
                          Upload a photo of a recipe, meal plan, or handwritten list
                        </p>
                        <div className="border-2 border-dashed border-stone-300 rounded-lg p-8 text-center">
                          <Camera className="h-12 w-12 text-stone-400 mx-auto mb-4" />
                          <p className="text-stone-600 mb-4">Drag and drop an image here, or click to browse</p>
                          <Button variant="outline" disabled className="border-stone-300 text-stone-700 bg-transparent">
                            <Upload className="h-4 w-4 mr-2" />
                            Upload Photo (Coming Soon)
                          </Button>
                        </div>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>

              {/* Quick Templates */}
              <Card className="border border-stone-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="text-stone-800">Quick Templates</CardTitle>
                  <CardDescription className="text-stone-600">
                    Start with pre-made templates for common meal plans
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 gap-3">
                    <Button
                      variant="outline"
                      className="h-auto p-4 flex flex-col items-start bg-transparent border-stone-300 text-stone-700 hover:bg-orange-50"
                      onClick={() =>
                        setAiPrompt(
                          "Weekly meal prep for healthy eating, including proteins, vegetables, and whole grains",
                        )
                      }
                    >
                      <span className="font-medium">Meal Prep</span>
                      <span className="text-xs text-stone-500">Healthy weekly prep</span>
                    </Button>

                    <Button
                      variant="outline"
                      className="h-auto p-4 flex flex-col items-start bg-transparent border-stone-300 text-stone-700 hover:bg-orange-50"
                      onClick={() => setAiPrompt("Family dinner ingredients for a week, kid-friendly meals")}
                    >
                      <span className="font-medium">Family Dinners</span>
                      <span className="text-xs text-stone-500">Kid-friendly meals</span>
                    </Button>

                    <Button
                      variant="outline"
                      className="h-auto p-4 flex flex-col items-start bg-transparent border-stone-300 text-stone-700 hover:bg-orange-50"
                      onClick={() => setAiPrompt("Vegetarian meals for the week with high protein options")}
                    >
                      <span className="font-medium">Vegetarian</span>
                      <span className="text-xs text-stone-500">Plant-based meals</span>
                    </Button>

                    <Button
                      variant="outline"
                      className="h-auto p-4 flex flex-col items-start bg-transparent border-stone-300 text-stone-700 hover:bg-orange-50"
                      onClick={() => setAiPrompt("Budget-friendly grocery list for basic meals under $50")}
                    >
                      <span className="font-medium">Budget Meals</span>
                      <span className="text-xs text-stone-500">Under $50</span>
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Generated Items */}
            <div className="space-y-6">
              <Card className="border border-stone-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center justify-between text-stone-800">
                    Generated Items
                    {generatedItems.length > 0 && (
                      <Badge variant="secondary" className="bg-stone-100 text-stone-600">
                        {generatedItems.length} items
                      </Badge>
                    )}
                  </CardTitle>
                  <CardDescription className="text-stone-600">
                    Review and modify your AI-generated grocery list
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {generatedItems.length === 0 ? (
                    <div className="text-center py-12 text-stone-400">
                      <ShoppingCart className="h-12 w-12 mx-auto mb-4 opacity-50" />
                      <p>No items generated yet.</p>
                      <p className="text-sm">Use one of the input methods to get started!</p>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      {generatedItems.map((item) => (
                        <div key={item.id} className="p-4 border border-stone-200 rounded-lg hover:bg-stone-50">
                          <div className="flex items-start justify-between">
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-2">
                                <h4 className="font-medium text-stone-800">{item.name}</h4>
                                <Badge variant="outline" className="text-xs border-stone-300 text-stone-600">
                                  {item.category}
                                </Badge>
                                <div className="flex items-center gap-1">
                                  <CheckCircle className="h-3 w-3 text-emerald-500" />
                                  <span className="text-xs text-stone-600">{item.confidence}% match</span>
                                </div>
                              </div>

                              {item.alternatives.length > 0 && (
                                <div className="mt-2">
                                  <p className="text-xs text-stone-600 mb-1">Alternatives:</p>
                                  <div className="flex flex-wrap gap-1">
                                    {item.alternatives.slice(0, 3).map((alt, index) => (
                                      <Badge
                                        key={index}
                                        variant="secondary"
                                        className="text-xs bg-stone-100 text-stone-600"
                                      >
                                        {alt}
                                      </Badge>
                                    ))}
                                  </div>
                                </div>
                              )}
                            </div>

                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => removeItem(item.id)}
                              className="text-red-600 hover:text-red-700 ml-2"
                            >
                              ×
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* AI Processing Status */}
              {isGenerating && (
                <Card className="border-orange-200 bg-orange-50">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3">
                      <div className="animate-spin">
                        <Sparkles className="h-6 w-6 text-orange-600" />
                      </div>
                      <div>
                        <h4 className="font-medium text-orange-800">AI Processing</h4>
                        <p className="text-sm text-orange-700">
                          Analyzing your request and generating optimized grocery items...
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Action Buttons */}
              {generatedItems.length > 0 && (
                <Card className="border border-stone-200 shadow-sm">
                  <CardContent className="p-6">
                    <div className="flex flex-col gap-3">
                      <Button size="lg" className="w-full bg-orange-500 hover:bg-orange-600 text-white" asChild>
                        <Link href="/dashboard">
                          <CheckCircle className="h-5 w-5 mr-2" />
                          Add {generatedItems.length} Items to List
                        </Link>
                      </Button>
                      <Button
                        variant="outline"
                        size="lg"
                        className="w-full bg-transparent border-stone-300 text-stone-700 hover:bg-stone-50"
                      >
                        <Wand2 className="h-5 w-5 mr-2" />
                        Optimize with AI
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/ListBuilder.vue
<template>
  <div class="min-h-screen">
    <header class="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50 h-20">
      <div class="container mx-auto px-4 h-full flex items-center justify-between">
        <button @click="backToDashboard" class="flex items-center space-x-3">
          <span class="text-white font-bold text-lg">🍊</span>
          <h1 class="text-2xl font-bold text-stone-800">tangerine</h1>
        </button>
        <div class="flex items-center space-x-4">
          <button @click="backToDashboard" class="px-4 py-2 border border-stone-300 text-stone-700 hover:bg-stone-50 bg-transparent rounded transition-colors">
            Back to Dashboard
          </button>
          <button v-if="generatedItems.length > 0" @click="saveList" :disabled="isSaving" class="px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded transition-colors flex items-center gap-2 disabled:bg-stone-400">
            Save List & View
          </button>
        </div>
      </div>
    </header>

    <div class="container mx-auto px-4 py-8">
      <div class="max-w-6xl mx-auto">
        <div class="text-center mb-8">
          <h2 class="text-3xl font-bold text-stone-800 mb-4">Build Your Grocery List</h2>
          <p class="text-lg text-stone-600">
            Use AI to generate optimized grocery lists from recipes, meal plans, or natural language
          </p>
        </div>

        <div class="grid lg:grid-cols-2 gap-8">
          <div class="space-y-6">
            <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
              <div class="p-6 border-b">
                <h3 class="text-lg font-medium text-stone-800">Name Your Grocery List</h3>
              </div>
              <div class="p-6">
                <input 
                  v-model="listName" 
                  placeholder="e.g., Weekly Groceries, Party Prep" 
                  class="w-full px-3 py-2 border border-stone-300 rounded-md" 
                />
              </div>
            </div>
            <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
              <div class="p-6 border-b">
                <h3 class="text-lg font-medium text-stone-800">Choose Your Input Method</h3>
              </div>
              <div class="p-6">
                <div class="grid w-full grid-cols-4 bg-stone-100 border-0 rounded-lg p-1 mb-6">
                  <button @click="inputMethod = 'manual'" :class="getTabClass('manual')">Manual</button>
                  <button @click="inputMethod = 'ai'" :class="getTabClass('ai')">AI Prompt</button>
                  <button @click="inputMethod = 'recipe'" :class="getTabClass('recipe')">Recipe</button>
                  <button @click="inputMethod = 'photo'" :class="getTabClass('photo')">Photo</button>
                </div>

                <div v-if="inputMethod === 'manual'" class="space-y-4">
                  <h4 class="font-medium mb-2 text-stone-800">Add Items Manually</h4>
                  <div class="flex gap-2">
                    <input v-model="manualItem" @keyup.enter="addManualItem" placeholder="e.g., 'milk', 'bananas'" class="flex-1 px-3 py-2 border border-stone-300 rounded-md" />
                    <button @click="addManualItem" class="px-3 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-md">
                      <Plus class="h-4 w-4" />
                    </button>
                  </div>
                </div>

                <div v-if="inputMethod === 'ai'" class="space-y-4">
                  <h4 class="font-medium mb-2 text-stone-800">AI-Powered Generation</h4>
                  <textarea v-model="aiPrompt" placeholder="e.g., 'Healthy meals for a family of 4 this week...'" class="w-full px-3 py-2 border border-stone-300 rounded-md min-h-[100px]"></textarea>
                  <button @click="generateAIList" :disabled="isGenerating || !aiPrompt.trim()" class="w-full mt-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 disabled:bg-stone-300 text-white rounded-md flex-center-gap">
                    <Clock v-if="isGenerating" class="h-4 w-4 animate-spin" />
                    <Sparkles v-else class="h-4 w-4" />
                    {{ isGenerating ? 'Generating...' : 'Generate List' }}
                  </button>
                </div>

                <div v-if="inputMethod === 'recipe'" class="space-y-4">
                  <h4 class="font-medium mb-2 text-stone-800">Recipe Analysis</h4>
                  <textarea v-model="recipe" placeholder="Paste your recipe here..." class="w-full px-3 py-2 border border-stone-300 rounded-md min-h-[120px]"></textarea>
                  <button @click="analyzeRecipe" :disabled="isGenerating || !recipe.trim()" class="w-full mt-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 disabled:bg-stone-300 text-white rounded-md flex-center-gap">
                    <Clock v-if="isGenerating" class="h-4 w-4 animate-spin" />
                    <FileText v-else class="h-4 w-4" />
                    {{ isGenerating ? 'Analyzing...' : 'Extract Ingredients' }}
                  </button>
                </div>

                <div v-if="inputMethod === 'photo'" class="space-y-4">
                  <h4 class="font-medium mb-2 text-stone-800">Photo Recognition</h4>
                  <div class="border-2 border-dashed border-stone-300 rounded-lg p-8 text-center">
                    <Camera class="h-12 w-12 text-stone-400 mx-auto mb-4" />
                    <p class="text-stone-600 mb-4">Drag and drop an image here</p>
                    <button disabled class="px-4 py-2 border border-stone-300 text-stone-700 bg-transparent rounded flex-center-gap mx-auto">
                      <Upload class="h-4 w-4" />
                      Upload Photo (Coming Soon)
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
              <div class="p-6 border-b">
                <h3 class="text-lg font-medium text-stone-800">Quick Templates</h3>
                <p class="text-stone-600 mt-1">Start with pre-made templates for common meal plans</p>
              </div>
              <div class="p-6 grid grid-cols-2 gap-3">
                <button @click="setTemplate('Weekly meal prep for healthy eating, including proteins, vegetables, and whole grains')" class="template-button">
                  <div class="font-medium text-stone-800">Meal Prep</div>
                  <div class="text-xs text-stone-500">Healthy weekly prep</div>
                </button>
                <button @click="setTemplate('Family dinner ingredients for a week, kid-friendly meals')" class="template-button">
                  <div class="font-medium text-stone-800">Family Dinners</div>
                  <div class="text-xs text-stone-500">Kid-friendly meals</div>
                </button>
              </div>
            </div>
          </div>

          <div class="space-y-6">
            <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
              <div class="p-6 border-b">
                <div class="flex items-center justify-between">
                  <h3 class="text-lg font-medium text-stone-800">Generated Items</h3>
                  <span v-if="generatedItems.length > 0" class="px-2 py-1 bg-stone-100 text-stone-600 text-sm rounded">{{ generatedItems.length }} items</span>
                </div>
              </div>
              <div class="p-6">
                <div v-if="isGenerating" class="text-center py-12 text-stone-500">
                    <div class="inline-block animate-spin"><Sparkles class="h-8 w-8 text-orange-500" /></div>
                    <p class="mt-4">AI is thinking...</p>
                </div>
                <div v-else-if="generatedItems.length === 0" class="text-center py-12 text-stone-400">
                  <ShoppingCart class="h-12 w-12 mx-auto mb-4 opacity-50" />
                  <p>No items generated yet.</p>
                </div>
                <div v-else class="space-y-3">
                  <div v-for="item in generatedItems" :key="item.id" class="flex items-center text-sm bg-stone-50 p-3 rounded-md shadow-sm">
                    <div class="flex-1">
                      <div class="flex justify-between items-start">
                        <div>
                          <p class="font-semibold text-stone-800">{{ item.name }} (x{{ item.quantity }})</p>
                          <p class="text-xs text-stone-500">{{ item.brand }} • {{ item.size }}</p>
                          <p class="text-xs text-stone-500">{{ item.fulfillment_type }} • <span :class="item.inventory === 'In Stock' ? 'text-emerald-600' : 'text-amber-600'">{{ item.inventory }}</span></p>
                        </div>
                        <div class="text-right">
                          <p v-if="item.promo_price" class="font-semibold text-emerald-600">${{ (parseFloat(item.promo_price) || 0).toFixed(2) }}</p>
                          <p :class="item.promo_price ? 'text-xs text-stone-400 line-through' : 'font-semibold text-stone-800'">
                            ${{ (parseFloat(item.price) || 0).toFixed(2) }}
                          </p>
                        </div>
                      </div>
                    </div>
                    <div class="ml-4 flex flex-col gap-2">
                      <button @click="swapItem(item.id)" class="text-blue-500 hover:text-blue-700 p-1" title="Swap Item">🔄</button>
                      <button @click="removeGeneratedItem(item.id)" class="text-red-500 hover:text-red-700 p-1" title="Remove Item">🗑️</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { userStore } from '@/stores/userStore';
import {
  ArrowRight, Plus, Sparkles, Clock, FileText, Camera, Upload, ShoppingCart
} from 'lucide-vue-next';

const router = useRouter();
const base_url = import.meta.env.VITE_API_BASE_URL;

const listName = ref('My Weekly Groceries');
const isSaving = ref(false);
const inputMethod = ref('ai');
const manualItem = ref('');
const aiPrompt = ref('');
const recipe = ref('');
const isGenerating = ref(false);
const generatedItems = ref([]);

// --- MOCK PRODUCT DATABASE ---
// MODIFIED: This is now the single source of truth for all mock products.
// It includes fulfillment_type and more variety.
const mockProductDatabase = [
  { name: 'Organic Milk', quantity: 1, price: 4.50, promo_price: null, brand: 'Horizon', size: 'Half Gallon', inventory: 'In Stock', category: 'Dairy', fulfillment_type: 'In-Store Pickup' },
  { name: 'Avocados', quantity: 3, price: 5.00, promo_price: 4.50, brand: 'Calavo', size: '3-pack', inventory: 'In Stock', category: 'Produce', fulfillment_type: 'In-Store Pickup' },
  { name: 'Sourdough Bread', quantity: 1, price: 5.99, promo_price: null, brand: 'Local Bakery', size: '1 loaf', inventory: 'Low Stock', category: 'Bakery', fulfillment_type: 'In-Store Pickup' },
  { name: 'Ground Turkey', quantity: 1, price: 6.99, promo_price: null, brand: 'Jennie-O', size: '1 lb', inventory: 'In Stock', category: 'Meat', fulfillment_type: 'Delivery' },
  { name: 'Spinach', quantity: 1, price: 3.50, promo_price: null, brand: 'Organic Girl', size: '5 oz', inventory: 'In Stock', category: 'Produce', fulfillment_type: 'Delivery' },
  { name: 'Chicken Breast', quantity: 2, price: 10.99, promo_price: null, brand: 'Tyson', size: '1.5 lbs', inventory: 'In Stock', category: 'Meat', fulfillment_type: 'In-Store Pickup' },
  { name: 'Broccoli', quantity: 1, price: 2.50, promo_price: null, brand: 'Fresh Farms', size: '1 bunch', inventory: 'In Stock', category: 'Produce', fulfillment_type: 'Delivery' },
  { name: 'Brown Rice', quantity: 1, price: 3.99, promo_price: null, brand: 'Uncle Ben\'s', size: '2 lb bag', inventory: 'In Stock', category: 'Grains', fulfillment_type: 'Shipping' },
  { name: 'Flour', quantity: 1, price: 3.49, promo_price: null, brand: 'Gold Medal', size: '5 lb bag', inventory: 'In Stock', category: 'Baking', fulfillment_type: 'Shipping' },
  { name: 'Eggs', quantity: 1, price: 4.99, promo_price: null, brand: 'Eggland\'s Best', size: '1 dozen', inventory: 'In Stock', category: 'Dairy', fulfillment_type: 'In-Store Pickup' },
];

const backToDashboard = () => {
  router.push('/dashboard');
};

const saveList = async () => {
  if (!listName.value.trim() || generatedItems.value.length === 0) return;
  isSaving.value = true;
  try {
    const payload = { name: listName.value, items: generatedItems.value };
    const response = await fetch(`${base_url}/api/grocery-list/create`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${userStore.token}`
      },
      body: JSON.stringify(payload)
    });
    if (!response.ok) throw new Error('Failed to save list.');
    router.push('/dashboard');
  } catch (error) {
    console.error("Error saving list:", error);
    alert("There was an error saving your list.");
  } finally {
    isSaving.value = false;
  }
};

const getTabClass = (method) => {
  const base = 'text-xs px-2 py-2 rounded transition-colors';
  return inputMethod.value === method ? `${base} bg-white text-stone-800 shadow-sm` : `${base} text-stone-600 hover:text-stone-800`;
};

const addManualItem = () => {
  if (!manualItem.value.trim()) return;
  generatedItems.value.push({
    id: Date.now(),
    name: manualItem.value.trim(),
    quantity: 1, price: 0.00, promo_price: null, brand: 'N/A', size: 'N/A',
    inventory: 'Unknown', category: 'Uncategorized', fulfillment_type: 'In-Store Pickup',
  });
  manualItem.value = '';
};

// MODIFIED: AI functions now pull random items from the mock database
const mockAPICall = (itemCount = 3) => {
  isGenerating.value = true;
  generatedItems.value = [];
  return new Promise(resolve => {
    setTimeout(() => {
      // Shuffle and pick a few random items
      const shuffled = [...mockProductDatabase].sort(() => 0.5 - Math.random());
      generatedItems.value = shuffled.slice(0, itemCount).map((item, index) => ({ id: Date.now() + index, ...item }));
      isGenerating.value = false;
      resolve();
    }, 1500);
  });
};

const generateAIList = () => {
  mockAPICall(4); // Generate 4 random items
};

const analyzeRecipe = () => {
  mockAPICall(3); // Generate 3 random items
};

const setTemplate = (template) => {
  inputMethod.value = 'ai';
  aiPrompt.value = template;
};

const removeGeneratedItem = (id) => {
  generatedItems.value = generatedItems.value.filter(item => item.id !== id);
};

const swapItem = (itemId) => {
  const itemIndex = generatedItems.value.findIndex(item => item.id === itemId);
  if (itemIndex > -1) {
    let newItem;
    do {
      newItem = mockProductDatabase[Math.floor(Math.random() * mockProductDatabase.length)];
    } while (newItem.name === generatedItems.value[itemIndex].name);
    
    generatedItems.value[itemIndex] = { ...newItem, id: itemId };
  }
};
</script>

<style scoped>
.flex-center-gap {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
}
.template-button {
  @apply p-4 border border-stone-300 rounded-lg hover:bg-orange-50 transition-colors text-left;
}
textarea {
  resize: vertical;
}
</style>
