// frontend/src/components/Profile.vue
<template>
  <div class="min-h-screen">
    <header class="border-b bg-white/80 backdrop-blur-sm h-20 sticky top-0 z-50">
      <div class="container mx-auto px-4 h-full flex items-center justify-between">
        <button @click="redirectToDashboard" class="flex items-center space-x-3">
          <span class="text-white font-bold text-lg">🍊</span>
          <h1 class="text-2xl font-bold text-stone-800">tangerine</h1>
        </button>
        <div class="flex items-center space-x-3">
          <button @click="redirectToDashboard" class="px-3 py-1 text-sm text-stone-600 hover:text-orange-600 hover:bg-orange-50 rounded transition-colors">
            Dashboard
          </button>
          <button @click="signOut" class="px-3 py-1 text-sm border border-stone-300 text-stone-700 hover:bg-stone-50 bg-transparent rounded transition-colors">
            Sign Out
          </button>
        </div>
      </div>
    </header>

    <div class="container mx-auto px-4 py-8">
      <div class="max-w-4xl mx-auto" v-if="editableProfile">
        <div class="mb-8">
          <h2 class="text-3xl font-bold text-stone-800 mb-2">Profile Settings</h2>
          <p class="text-lg text-stone-600">Manage your account and preferences, {{ editableProfile.firstName || 'user' }}.</p>
        </div>

        <div class="space-y-8">
          <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
            <div class="p-6 border-b">
              <h3 class="text-lg font-medium text-stone-800">Basic Information</h3>
            </div>
            <div class="p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">First Name</label>
                <input v-model="editableProfile.firstName" class="w-full px-3 py-2 border border-stone-300 rounded-md"/>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Last Name</label>
                <input v-model="editableProfile.lastName" class="w-full px-3 py-2 border border-stone-300 rounded-md"/>
              </div>
              <div class="md:col-span-2">
                <label class="block text-sm font-medium text-stone-700 mb-1">Email</label>
                <input :value="editableProfile.email" disabled class="w-full px-3 py-2 border border-stone-300 rounded-md bg-stone-100 text-stone-500 cursor-not-allowed"/>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Location (ZIP Code)</label>
                <input v-model="editableProfile.preferredLocation" class="w-full px-3 py-2 border border-stone-300 rounded-md"/>
              </div>

              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Age</label>
                <input type="number" v-model.number="editableProfile.age" placeholder="e.g., 30" class="w-full px-3 py-2 border border-stone-300 rounded-md"/>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Gender</label>
                <select v-model="editableProfile.gender" class="w-full px-3 py-2 border border-stone-300 rounded-md">
                   <option disabled value="">Select...</option>
                   <option>Male</option>
                   <option>Female</option>
                   <option>Non-binary</option>
                   <option>Prefer not to say</option>
                </select>
              </div>
              </div>
          </div>

          <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
            <div class="p-6 border-b">
              <h3 class="text-lg font-medium text-stone-800">Budget & Shopping</h3>
            </div>
            <div class="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div class="md:col-span-2">
                <label class="block text-sm font-medium text-stone-700 mb-2">Weekly Grocery Budget: <span class="font-semibold text-orange-600">${{ editableProfile.budget }}</span></label>
                <input type="range" v-model.number="editableProfile.budget" min="50" max="500" step="5" class="w-full h-2 bg-stone-200 rounded-lg appearance-none cursor-pointer"/>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Shopping Frequency</label>
                <select v-model="editableProfile.shoppingFrequency" class="w-full px-3 py-2 border border-stone-300 rounded-md">
                  <option>Daily</option>
                  <option>Weekly</option>
                  <option>Bi-weekly</option>
                  <option>Monthly</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Shopping Priority</label>
                <select v-model="editableProfile.shoppingPriority" class="w-full px-3 py-2 border border-stone-300 rounded-md">
                  <option>Lowest Cost</option>
                  <option>Highest Quality</option>
                  <option>Healthiest Options</option>
                  <option>Convenience</option>
                  <option>Balanced Approach</option>
                </select>
              </div>
            </div>
          </div>

          <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
            <div class="p-6 border-b">
              <h3 class="text-lg font-medium text-stone-800">Dietary & Health</h3>
            </div>
            <div class="p-6 space-y-4">
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-3">Dietary Restrictions</label>
                <div class="flex flex-wrap gap-2">
                  <button v-for="diet in dietaryRestrictions" :key="diet" @click="toggleSelection(editableProfile.dietaryRestrictions, diet)" :class="getButtonClass(editableProfile.dietaryRestrictions.includes(diet), 'orange')">
                    {{ diet }}
                  </button>
                </div>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-3">Allergies</label>
                <div class="flex flex-wrap gap-2">
                  <button v-for="allergy in commonAllergies" :key="allergy" @click="toggleSelection(editableProfile.allergies, allergy)" :class="getButtonClass(editableProfile.allergies.includes(allergy), 'orange')">
                    {{ allergy }}
                  </button>
                </div>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Health Goals (Optional)</label>
                <textarea v-model="editableProfile.healthGoals" placeholder="e.g., lose weight, build muscle..." class="w-full px-3 py-2 border border-stone-300 rounded-md min-h-[80px] resize-none"></textarea>
              </div>
            </div>
          </div>
          
          <div class="bg-white border border-stone-200 shadow-sm rounded-lg">
            <div class="p-6 border-b">
              <h3 class="text-lg font-medium text-stone-800">Taste Preferences</h3>
            </div>
            <div class="p-6 space-y-4">
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-3">Favorite Cuisines</label>
                <div class="flex flex-wrap gap-2">
                  <button v-for="cuisine in cuisinePreferences" :key="cuisine" @click="toggleSelection(editableProfile.favoriteCuisines, cuisine)" :class="getButtonClass(editableProfile.favoriteCuisines.includes(cuisine), 'orange')">
                    {{ cuisine }}
                  </button>
                </div>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Cultural Background (Optional)</label>
                <input v-model="editableProfile.culturalBackground" placeholder="e.g., Italian-American, Mexican..." class="w-full px-3 py-2 border border-stone-300 rounded-md"/>
              </div>
              <div>
                <label class="block text-sm font-medium text-stone-700 mb-1">Favorite Foods & Ingredients (Optional)</label>
                <textarea v-model="editableProfile.favoriteFoods" placeholder="e.g., I love spicy food, fresh pasta..." class="w-full px-3 py-2 border border-stone-300 rounded-md min-h-[80px] resize-none"></textarea>
              </div>
            </div>
          </div>
          
          <div class="flex justify-end items-center gap-4">
            <p v-if="statusMessage" :class="statusMessageColor" class="text-sm transition-opacity duration-300">{{ statusMessage }}</p>
            <button @click="saveChanges" class="px-6 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg transition-colors">
              Save Changes
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRouter } from 'vue-router';
import { userStore } from '@/stores/userStore';

const router = useRouter();
const base_url = import.meta.env.VITE_API_BASE_URL;

const editableProfile = ref(null);
const statusMessage = ref('');
const isError = ref(false);

const dietaryRestrictions = ref(['Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Keto', 'Paleo', 'Pescatarian', 'Halal', 'Kosher']);
const commonAllergies = ref(['Peanuts', 'Tree Nuts', 'Dairy', 'Eggs', 'Soy', 'Wheat', 'Fish', 'Shellfish']);
const cuisinePreferences = ref(['American', 'Italian', 'Mexican', 'Chinese', 'Indian', 'Japanese', 'Mediterranean', 'Thai', 'French', 'Korean']);

onMounted(() => {
  if (userStore.user) {
    editableProfile.value = JSON.parse(JSON.stringify(userStore.user));
  } else {
    router.push('/login');
  }
});

const saveChanges = async () => {
  if (!editableProfile.value) return;
  try {
    const response = await fetch(`${base_url}/api/user/update-profile`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${userStore.token}`
      },
      body: JSON.stringify(editableProfile.value)
    });
    if (!response.ok) throw new Error('Failed to save profile.');
    
    await userStore.fetchUser();
    isError.value = false;
    statusMessage.value = 'Profile saved successfully!';
  } catch (error) {
    console.error('Error saving profile:', error);
    isError.value = true;
    statusMessage.value = 'Failed to save. Please try again.';
  } finally {
    setTimeout(() => { statusMessage.value = ''; }, 3000);
  }
};

const toggleSelection = (selectionArray, item) => {
  if (!selectionArray) {
    selectionArray = [];
  }
  const index = selectionArray.indexOf(item);
  if (index > -1) {
    selectionArray.splice(index, 1);
  } else {
    selectionArray.push(item);
  }
};

const getButtonClass = (isSelected, color) => {
  const base = 'px-3 py-1 text-sm rounded-full border transition-colors cursor-pointer';
  if (isSelected) {
    return `${base} bg-${color}-500 text-white border-${color}-500`;
  }
  return `${base} border-stone-300 text-stone-600 hover:bg-${color}-50`;
};

const statusMessageColor = computed(() => {
  return isError.value ? 'text-red-600' : 'text-emerald-600';
});

const redirectToDashboard = () => router.push('/dashboard');
const signOut = () => {
  userStore.logout();
  router.push('/login');
};
</script>

<style scoped>
input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 1rem;
  height: 1rem;
  background: #f97316; /* orange-500 */
  border-radius: 9999px;
  cursor: pointer;
  margin-top: -4px;
}
input[type="range"]::-moz-range-thumb {
  width: 1rem;
  height: 1rem;
  background: #f97316; /* orange-500 */
  border-radius: 9999px;
  cursor: pointer;
}
</style>

// frontend/app/profile/page.tsx
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Badge } from "@/components/ui/badge"
import { User, DollarSign, Heart, Globe, ArrowRight } from "lucide-react"
import Link from "next/link"
import Image from "next/image"

export default function ProfilePage() {
  const [budget, setBudget] = useState([200])
  const [selectedDiets, setSelectedDiets] = useState<string[]>([])
  const [selectedCuisines, setSelectedCuisines] = useState<string[]>([])
  const [selectedAllergies, setSelectedAllergies] = useState<string[]>([])

  const dietaryRestrictions = [
    "Vegetarian",
    "Vegan",
    "Gluten-Free",
    "Keto",
    "Paleo",
    "Low-Carb",
    "Dairy-Free",
    "Nut-Free",
  ]

  const cuisinePreferences = [
    "Italian",
    "Mexican",
    "Asian",
    "Mediterranean",
    "Indian",
    "American",
    "French",
    "Thai",
    "Japanese",
    "Middle Eastern",
  ]

  const commonAllergies = ["Nuts", "Dairy", "Eggs", "Soy", "Wheat", "Fish", "Shellfish", "Sesame"]

  const toggleSelection = (item: string, list: string[], setList: (list: string[]) => void) => {
    if (list.includes(item)) {
      setList(list.filter((i) => i !== item))
    } else {
      setList([...list, item])
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 to-amber-50">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm h-20">
        <div className="container mx-auto px-4 h-full flex items-center justify-between">
          <Link href="/" className="flex items-center space-x-3">
            <Image
              src="/images/tangerine-logo.png"
              alt="Tangerine Logo"
              width={60}
              height={60}
              className="rounded-full"
            />
            <h1 className="text-2xl font-bold text-stone-800">tangerine profile</h1>
          </Link>
          <Button
            variant="outline"
            asChild
            className="border-stone-300 text-stone-700 hover:bg-stone-50 bg-transparent"
          >
            <Link href="/dashboard">Skip to Dashboard</Link>
          </Button>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-stone-800 mb-4">Create Your Taste Profile</h2>
            <p className="text-lg text-stone-600">
              Help us understand your preferences to provide personalized grocery recommendations
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Basic Information */}
            <Card className="border border-stone-200 shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-stone-800">
                  <User className="h-5 w-5 text-orange-600" />
                  Basic Information
                </CardTitle>
                <CardDescription className="text-stone-600">Tell us about yourself and your household</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="firstName" className="text-stone-700">
                      First Name
                    </Label>
                    <Input id="firstName" placeholder="John" className="border-stone-300" />
                  </div>
                  <div>
                    <Label htmlFor="lastName" className="text-stone-700">
                      Last Name
                    </Label>
                    <Input id="lastName" placeholder="Doe" className="border-stone-300" />
                  </div>
                </div>

                <div>
                  <Label htmlFor="email" className="text-stone-700">
                    Email
                  </Label>
                  <Input id="email" type="email" placeholder="john@example.com" className="border-stone-300" />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="age" className="text-stone-700">
                      Age Range
                    </Label>
                    <Select>
                      <SelectTrigger className="border-stone-300">
                        <SelectValue placeholder="Select age range" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="18-25">18-25</SelectItem>
                        <SelectItem value="26-35">26-35</SelectItem>
                        <SelectItem value="36-45">36-45</SelectItem>
                        <SelectItem value="46-55">46-55</SelectItem>
                        <SelectItem value="56+">56+</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="household" className="text-stone-700">
                      Household Size
                    </Label>
                    <Select>
                      <SelectTrigger className="border-stone-300">
                        <SelectValue placeholder="Select size" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1">1 person</SelectItem>
                        <SelectItem value="2">2 people</SelectItem>
                        <SelectItem value="3">3 people</SelectItem>
                        <SelectItem value="4">4 people</SelectItem>
                        <SelectItem value="5+">5+ people</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div>
                  <Label htmlFor="location" className="text-stone-700">
                    Location (ZIP Code)
                  </Label>
                  <Input id="location" placeholder="12345" className="border-stone-300" />
                </div>
              </CardContent>
            </Card>

            {/* Budget Preferences */}
            <Card className="border border-stone-200 shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-stone-800">
                  <DollarSign className="h-5 w-5 text-amber-600" />
                  Budget & Shopping Preferences
                </CardTitle>
                <CardDescription className="text-stone-600">Set your budget and shopping frequency</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div>
                  <Label className="text-base font-medium text-stone-700">Weekly Grocery Budget</Label>
                  <div className="mt-2">
                    <Slider value={budget} onValueChange={setBudget} max={500} min={50} step={25} className="w-full" />
                    <div className="flex justify-between text-sm text-stone-500 mt-1">
                      <span>$50</span>
                      <span className="font-medium text-orange-600">${budget[0]}</span>
                      <span>$500+</span>
                    </div>
                  </div>
                </div>

                <div>
                  <Label htmlFor="shopping-frequency" className="text-stone-700">
                    Shopping Frequency
                  </Label>
                  <Select>
                    <SelectTrigger className="border-stone-300">
                      <SelectValue placeholder="How often do you shop?" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="daily">Daily</SelectItem>
                      <SelectItem value="weekly">Weekly</SelectItem>
                      <SelectItem value="biweekly">Bi-weekly</SelectItem>
                      <SelectItem value="monthly">Monthly</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="priority" className="text-stone-700">
                    Shopping Priority
                  </Label>
                  <Select>
                    <SelectTrigger className="border-stone-300">
                      <SelectValue placeholder="What matters most?" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="cost">Lowest Cost</SelectItem>
                      <SelectItem value="quality">Highest Quality</SelectItem>
                      <SelectItem value="health">Healthiest Options</SelectItem>
                      <SelectItem value="convenience">Convenience</SelectItem>
                      <SelectItem value="balanced">Balanced Approach</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </CardContent>
            </Card>

            {/* Dietary Restrictions */}
            <Card className="border border-stone-200 shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-stone-800">
                  <Heart className="h-5 w-5 text-red-600" />
                  Dietary Restrictions & Health
                </CardTitle>
                <CardDescription className="text-stone-600">
                  Select any dietary restrictions or health considerations
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label className="text-base font-medium mb-3 block text-stone-700">Dietary Restrictions</Label>
                  <div className="flex flex-wrap gap-2">
                    {dietaryRestrictions.map((diet) => (
                      <Badge
                        key={diet}
                        variant={selectedDiets.includes(diet) ? "default" : "outline"}
                        className={`cursor-pointer transition-colors ${
                          selectedDiets.includes(diet)
                            ? "bg-orange-500 text-white hover:bg-orange-600"
                            : "border-stone-300 text-stone-600 hover:bg-orange-50"
                        }`}
                        onClick={() => toggleSelection(diet, selectedDiets, setSelectedDiets)}
                      >
                        {diet}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <Label className="text-base font-medium mb-3 block text-stone-700">Allergies</Label>
                  <div className="flex flex-wrap gap-2">
                    {commonAllergies.map((allergy) => (
                      <Badge
                        key={allergy}
                        variant={selectedAllergies.includes(allergy) ? "destructive" : "outline"}
                        className={`cursor-pointer transition-colors ${
                          selectedAllergies.includes(allergy)
                            ? "bg-red-500 text-white hover:bg-red-600"
                            : "border-stone-300 text-stone-600 hover:bg-red-50"
                        }`}
                        onClick={() => toggleSelection(allergy, selectedAllergies, setSelectedAllergies)}
                      >
                        {allergy}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <Label htmlFor="health-goals" className="text-stone-700">
                    Health Goals (Optional)
                  </Label>
                  <Textarea
                    id="health-goals"
                    placeholder="e.g., lose weight, build muscle, improve heart health..."
                    className="mt-1 border-stone-300"
                  />
                </div>
              </CardContent>
            </Card>

            {/* Cultural Preferences */}
            <Card className="border border-stone-200 shadow-sm">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-stone-800">
                  <Globe className="h-5 w-5 text-amber-600" />
                  Cultural & Taste Preferences
                </CardTitle>
                <CardDescription className="text-stone-600">
                  Help us understand your cultural background and taste preferences
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label className="text-base font-medium mb-3 block text-stone-700">Favorite Cuisines</Label>
                  <div className="flex flex-wrap gap-2">
                    {cuisinePreferences.map((cuisine) => (
                      <Badge
                        key={cuisine}
                        variant={selectedCuisines.includes(cuisine) ? "default" : "outline"}
                        className={`cursor-pointer transition-colors ${
                          selectedCuisines.includes(cuisine)
                            ? "bg-amber-500 text-white hover:bg-amber-600"
                            : "border-stone-300 text-stone-600 hover:bg-amber-50"
                        }`}
                        onClick={() => toggleSelection(cuisine, selectedCuisines, setSelectedCuisines)}
                      >
                        {cuisine}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div>
                  <Label htmlFor="cultural-background" className="text-stone-700">
                    Cultural Background (Optional)
                  </Label>
                  <Input
                    id="cultural-background"
                    placeholder="e.g., Italian-American, Mexican, Indian..."
                    className="border-stone-300"
                  />
                </div>

                <div>
                  <Label htmlFor="cooking-level" className="text-stone-700">
                    Cooking Experience
                  </Label>
                  <Select>
                    <SelectTrigger className="border-stone-300">
                      <SelectValue placeholder="How would you rate your cooking skills?" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="beginner">Beginner</SelectItem>
                      <SelectItem value="intermediate">Intermediate</SelectItem>
                      <SelectItem value="advanced">Advanced</SelectItem>
                      <SelectItem value="expert">Expert/Professional</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="favorite-foods" className="text-stone-700">
                    Favorite Foods & Ingredients
                  </Label>
                  <Textarea
                    id="favorite-foods"
                    placeholder="Tell us about foods you love, ingredients you use often, or dishes you enjoy cooking..."
                    className="mt-1 border-stone-300"
                  />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Action Buttons */}
          <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="text-lg px-8 py-3 bg-orange-500 hover:bg-orange-600 text-white" asChild>
              <Link href="/dashboard" className="flex items-center gap-2">
                Create Profile & Continue
                <ArrowRight className="h-5 w-5" />
              </Link>
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="text-lg px-8 py-3 bg-transparent border-stone-300 text-stone-700 hover:bg-stone-50"
              asChild
            >
              <Link href="/">Back to Home</Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
